### ISSUE TITLE
BERT Training Epoch Number

### ISSUE THREAD

**Issue by SUDA-HLT-ywfang** [zliucr/CrossNER#1]
Hi,
    Thank you for opening source you work. In run_language_modeling.py, I notice that you set "num_train_epochs" as 15. Is there any reason doing that? Because default value in huggingface script is 3. And there isn't an evaluation file. Is there any risk of overfitting?

**Comment by zliucr** [comment]
Hi,
Thanks for your questions. Actually, "num_train_epochs" is a tunable hyper-parameter. In our experiments, we find out that setting "num_train_epochs" as 15 (or around 15) would be a good pre-training setting.
And in the code, we save the model in each epoch. You can try the model with less pre-training epochs when overfitting happens.

**Comment by SUDA-HLT-ywfang** [comment]
Thanks for your quick reply. I think that answers my question.
BTW, I think there is a small bug when directly running run_language_modeling.py. Function "pad_sequence" is not defined. You should import it from "torch.nn.utils.rnn".
