### ISSUE TITLE
Vocab files

### ISSUE THREAD

**Issue by alejosierra** [zliucr/CrossNER#5]
Hello, 

Thank you for sharing the code and the datasets.
I am trying to reproduce the experiments, but I am getting an error because the vocab.txt file is not present in any of the domain folders
I am trying to run the baseline
`python main.py --exp_name politics_bilstm_wordchar --exp_id 1 --tgt_dm politics --bilstm --dropout 0.3 --lr 1e-3 --usechar --emb_dim 400`
but i am getting the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'ner_data/conll2003/vocab.txt'`

Maybe I am missing some step to generate the vocab files

Regards,

**Comment by zliucr** [comment]
Hi,

Sorry that we forget to provide the vocab file, it will be updated soon. And you can also easily generate the vocab file based on the dataset we release.

**Comment by alejosierra** [comment]
Thanks.
Is this just a file with the set of all the tokens in the dataset? I did generate it that way to run the experiment but I wasn't sure that was the right way to do it.

**Comment by zliucr** [comment]
yes. that should be the right way.
