### ISSUE TITLE
Pre-training source domain stops on the 2nd epoch

### ISSUE THREAD

**Issue by alejosierra** [zliucr/CrossNER#6]
Hi I have another question regarding the pre-training in the source domain (conll) when doing pre-train and then fine-tune.
Here [https://github.com/zliucr/CrossNER/blob/2e7ba2a7798c961e3f29fbc51252c5a8d40224bf/src/trainer.py#L121](https://github.com/zliucr/CrossNER/blob/2e7ba2a7798c961e3f29fbc51252c5a8d40224bf/src/trainer.py#L121) the training is set to stop after 2 epochs. Is this by design? I could not find something about that in the paper.

**Comment by zliucr** [comment]
Hi, we find that if pre-training on conll for too many epochs, it might hurt the performance on the target domains. So, we stop the training after 2 epochs.

**Comment by alejosierra** [comment]
Thank you for your answer
