### ISSUE TITLE
Pre-train then Fine-tune Comparing with Jointly Train

### ISSUE THREAD

**Issue by luoqiaoyang** [zliucr/CrossNER#7]
Hi, I am a little bit confused about the Pre-train meaning in this paper. It seems like sometimes the Pre-train refers to span-level MLM task and sometimes refers to NER task. 
According to the repo, the Pre-train on source domain in **Pre-train then Fine-tune** is to perform NER task on source domain instead of performing MLM task. So the main difference between **Pre-rain then Fine-tune** and **Jointly Train** is whether train source domain at first and then select the best model to train on target domain or mix up source domain and target domain data (also including the target domain augmentation) in single training stage. Do I understand it correctly?

**Comment by zliucr** [comment]
Yes, your understanding is correct. 
And you are right, it might cause some confusion between the domain-adaptive pre-training and Pre-train then Fine-tune. Actually, the domain-adaptive pre-training refers to the span-level MLM task.

**Comment by luoqiaoyang** [comment]
Thanks for your answer.
